services:
  erpnext:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_TYPE=${DB_TYPE:-postgres}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-erpnext}
      - DB_ROOT_USER=${DB_ROOT_USER:-postgres}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-postgres}
      - SITE_NAME=${SITE_NAME:-site.local}
