services:
  erpnext:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - SITE_NAME=${SITE_NAME:-site.local}
