#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
EXPORT_DIR="${SCRIPT_DIR}/exports"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

if [ -f "$ENV_FILE" ]; then
    set -a
    . "$ENV_FILE"
    set +a
fi

DB_NAME="${DB_NAME:-erpnext}"
DB_ROOT_PASSWORD="${DB_ROOT_PASSWORD:-root}"
MARIADB_SERVICE="${MARIADB_SERVICE:-mariadb}"
SCHEMA_FILE="${EXPORT_DIR}/${DB_NAME}_schema_${TIMESTAMP}.sql"
UPSERT_FILE="${EXPORT_DIR}/${DB_NAME}_upsert_${TIMESTAMP}.sql"
MAX_WAIT_SECONDS="${MAX_WAIT_SECONDS:-60}"

mkdir -p "$EXPORT_DIR"

compose() {
    docker compose -f "$COMPOSE_FILE" "$@"
}

mysql_exec() {
    compose exec -T "$MARIADB_SERVICE" mysql -uroot -p"$DB_ROOT_PASSWORD" --batch --skip-column-names "$@"
}

mysqldump_exec() {
    compose exec -T "$MARIADB_SERVICE" mysqldump -uroot -p"$DB_ROOT_PASSWORD" "$@"
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

command -v docker >/dev/null 2>&1 || die "docker is not installed or not in PATH"

[ -n "$DB_ROOT_PASSWORD" ] || die "DB_ROOT_PASSWORD is empty. Set it in .env before running this export."

echo "Checking MariaDB container availability..."
compose ps "$MARIADB_SERVICE" >/dev/null

SERVICE_STATE="$(compose ps --status running --services 2>/dev/null | grep -Fx "$MARIADB_SERVICE" || true)"
[ -n "$SERVICE_STATE" ] || die "service '$MARIADB_SERVICE' is not running. Start it with: docker compose up -d $MARIADB_SERVICE"

echo "Waiting for MariaDB to accept connections..."
START_TIME="$(date +%s)"
until mysql_exec -e "SELECT 1" >/dev/null 2>&1; do
    NOW="$(date +%s)"
    if [ $((NOW - START_TIME)) -ge "$MAX_WAIT_SECONDS" ]; then
        die "MariaDB did not become ready within ${MAX_WAIT_SECONDS}s. Check: docker compose logs $MARIADB_SERVICE"
    fi
    sleep 2
done

echo "Exporting schema to ${SCHEMA_FILE}"
mysqldump_exec \
    --single-transaction \
    --no-data \
    --routines \
    --triggers \
    --events \
    "$DB_NAME" > "$SCHEMA_FILE"

echo "Exporting data as upserts to ${UPSERT_FILE}"
{
    cat <<EOF
-- Generated by export-mariadb-upsert.sh on $(date -Iseconds)
-- Database: ${DB_NAME}
SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

EOF
} > "$UPSERT_FILE"

TABLES="$(mysql_exec -e "SELECT table_name FROM information_schema.tables WHERE table_schema = '${DB_NAME}' AND table_type = 'BASE TABLE' ORDER BY table_name")"

if [ -z "$TABLES" ]; then
    echo "No tables found in database ${DB_NAME}."
else
    while IFS= read -r table_name; do
        [ -z "$table_name" ] && continue

        column_list="$(mysql_exec -e "SELECT GROUP_CONCAT(CONCAT('`', column_name, '`') ORDER BY ordinal_position SEPARATOR ', ') FROM information_schema.columns WHERE table_schema = '${DB_NAME}' AND table_name = '${table_name}'")"

        if [ -z "$column_list" ]; then
            continue
        fi

        update_list="$(mysql_exec -e "SELECT GROUP_CONCAT(CONCAT('`', column_name, '` = VALUES(`', column_name, '`)') ORDER BY ordinal_position SEPARATOR ', ') FROM information_schema.columns WHERE table_schema = '${DB_NAME}' AND table_name = '${table_name}'")"

        if [ -z "$update_list" ]; then
            continue
        fi

        echo "Processing table ${table_name}"
        printf '\n-- Table: %s\n' "$table_name" >> "$UPSERT_FILE"

        mysqldump_exec \
            --single-transaction \
            --skip-triggers \
            --no-create-info \
            --skip-comments \
            --complete-insert \
            --extended-insert=FALSE \
            "$DB_NAME" "$table_name" | awk -v update_clause="$update_list" '
                /^INSERT INTO / {
                    sub(/;[[:space:]]*$/, "")
                    print $0 " ON DUPLICATE KEY UPDATE " update_clause ";"
                }
            ' >> "$UPSERT_FILE"
    done <<< "$TABLES"
fi

{
    cat <<EOF

SET UNIQUE_CHECKS=1;
SET FOREIGN_KEY_CHECKS=1;
EOF
} >> "$UPSERT_FILE"

echo "Done."
echo "Schema file: $SCHEMA_FILE"
echo "Upsert file: $UPSERT_FILE"